# Generated by Django 4.2.7 on 2024-01-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_accountstock_average_sell_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstock',
            name='average_buy_cost',
            field=models.IntegerField(default=0),
        ),
    ]
